### ISSUE TITLE
[Request, Feat] UIView 공통된 background shadow Extension 추가

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MC3-Team2-Ddoongs#16]
# UIView Extension 추가
- WordDetailView에서 단어에 들어가는 설명들에 대한 카드의 background shadow, color등에 관련해서 공통되는 코드가 많아져 UIView의 extension으로 빼려고 합니다.
   - extension 추가 하는데 문제될 점이 있을까요??
   - 문제될 점이 없다면, 현재까지의 작업상황(feat/11-wordDetailUsageRelatedUI 브랜치) PR 이후 새로운 브랜치에서 작업하겠습니다.(extension을 변경하셨거나 이 이슈 확인해주신 분은 확인 댓글 남겨주세요!)

<img src="https://user-images.githubusercontent.com/72736657/180637935-45739d9b-1a7e-42ca-bf34-d017b1476e1b.png" width=250>

## Completion conditions(To-do)

- [ ] CardView 뒤의 공통된 배경 extension으로 빼놓기

## Related issues

- Related issue1 (#7 )
- Related issue2 (#11 )

**Comment by GODNOEL** [comment]
너무 좋은 생각인것같습니다!!  완전 동의합니다. ✌️ ✌️✌️✌️

**Comment by sunshiningsoo** [comment]
> 너무 좋은 생각인것같습니다!! 완전 동의합니다. ✌️ ✌️✌️✌️

👍🙌🫡😆🤝❗️

**Comment by sunshiningsoo** [comment]
#37 develop로 merge!
