### ISSUE TITLE
[Request] default 브랜치 main -> develop으로 바꾸기

### ISSUE THREAD

**Issue by sunshiningsoo** [DeveloperAcademy-POSTECH/MC3-Team2-Ddoongs#21]
# default로 설정되어 있는 브랜치 **main -> develop**으로 바꾸어 놓는 작업이 필요할 것 같습니다.
- default로 설정되어 있는 브랜치가 main이라 매번 PR시마다 체크해주어야 하고, 그 과정에서 실수가 일어날 수 있는 여지가 많아보입니다.

괜찮으신것 같으면 댓글이나 반응 남겨주세요~~~🙃

**Comment by kyustudyo** [comment]
오 좋습니다 !

**Comment by GODNOEL** [comment]
좋아요!

**Comment by sunshiningsoo** [comment]
올라온 PR 처리후 설정예정
