### ISSUE TITLE
[Feat] Draw KeyboardUI

### ISSUE THREAD

**Issue by jinwp** [DeveloperAcademy-POSTECH/MC3-Team2-Ddoongs#3]
# Custom Keyboard UI 를 만듭니다
- Draw KeyboardUI

<img width="333" alt="스크린샷 2022-07-21 오후 5 25 41" src="https://user-images.githubusercontent.com/95157024/180167257-ef7e7f9d-2048-4845-9958-caec30967318.png">

## Completion conditions(To-do)

- [x] Create rows of UIButtons, and put them together.
- [ ] Text should be written in the selected text field when keyboard buttons are clicked.
- [ ] Add vertical Scroll View inside the keyboard

**Comment by sunshiningsoo** [comment]
Good Job!
