### ISSUE TITLE
[Feat] K-pop Slang - UITableView, Custom Cell 제작

### ISSUE THREAD

**Issue by Genesis2010** [DeveloperAcademy-POSTECH/MC3-Team2-Ddoongs#5]
# WordListView ( UITableView ) 와 Cell 을 Custom 하려고 합니다.
- 단어를 볼 수있는 List 형태로 화면을 구현하고자 UITableView 를 사용
- TableView 에 있는 각 cell 을 다음과 같은 이미지와 같이 custom

<img width="272" alt="스크린샷 2022-07-23 오전 2 45 58" src="https://user-images.githubusercontent.com/45564605/180495621-b9969049-a722-44c9-93fc-0127c316319f.png">

## Completion conditions(To-do)

- [ ] UITableView, Controller 를 사용하여 화면을 구성합니다.
- [ ] TableView 구성을 위해 더미 데이터를 생성합니다.
- [ ] 각 Cell 에 hangleName, EnglishName, favoriteButton 을 구성하고 custom 합니다.

## Related issues
- 없음

**Comment by sunshiningsoo** [comment]
#17 develop 브랜치로 머지후 이슈 닫음
